version: "3.9"

services:
  vite-app:
    image: keyword-genius
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5174:5174" # host:container
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["pnpm", "dev"]
    stdin_open: true
    tty: true
